Iter5
avGenie/url-shortener pull request #5
Opened 2024-02-07 05:39 UTC by avGenie

2024-02-08 07:36 UTC, popoffvg requested changes

2024-02-08 07:36 UTC, popoffvg commented on cmd/client/main.go
> +	"gopkg.in/h2non/gentleman.v2"
Не стоит использовать эту библиотеку, т.к. она не поддерживает пакет context (будет дальше в курсе). 

В курсе вплоть до первого проекта лучше использовать стандартную библиотеку, чтобы понять ее недостатки и каким требованиям должен  удоволетворять сторонний пакет.

2024-02-08 07:36 UTC, popoffvg commented on internal/app/config/config.go
> +	Config config
лучше не использовать глобальные переменные, т.к. это затрудняет тестирование

2024-02-08 07:36 UTC, popoffvg commented on cmd/shortener/main.go
> +	if err != nil {
всегда стоит проверять на ошибку ErrServerClosed, т.к. это ошибка возвращается при корректном завершении сервера

2024-02-08 07:36 UTC, popoffvg commented on internal/app/handlers/handlers.go
> +	fmt.Println("PostHandler")
Не стоит оставлять отладочную информацию в проекте

2024-02-08 07:36 UTC, popoffvg commented on internal/app/handlers/handlers.go
> +	bodyBytes, err := io.ReadAll(req.Body)
тело всегда надо закрывать после чтения и проверки на ошибку, вызвав req.Body.Close.

2024-02-08 07:36 UTC, popoffvg commented on internal/app/handlers/handlers.go
> +	urls[shortURL] = bodyString
Мапа в данном случае глобальная переменная, доступная из нескольких горутин. 
При каждом запросе к серверу создается отдельная горутина. Мапа не является конкурентно безопасной и паникует, если выполняется параллельная запись. 

Т.к. используется base64, то хранить значение на данном этапе необязательно. Либо можно закыть мапу мьютексами

2024-02-08 07:36 UTC, popoffvg commented on internal/app/handlers/handlers.go
> +	urls = make(map[string]string)
Лучше не использовать глобальные переменные, т.к. их использование затрудняет поддержку приложения. 

И сразу привыкать использовать везде локальные переменные.

2024-02-08 07:36 UTC, popoffvg commented on internal/app/handlers/handlers_test.go
> +		if test.isError {
Стоит всегда пытаться переписать констуркции if else на ранний return.

2024-02-08 07:36 UTC, popoffvg commented on internal/app/handlers/handlers_test.go
> +	ts := testCreateServer(t)
Для тестирования хендлеров стоит воспользоваться методами http.NewRecorder, т.к. они позволяют более изолированного выполнить тесты. 

Пример: https://gist.github.com/p4tin/64cf99e30b034ee100b9

2024-02-12 06:54 UTC, avGenie commented on internal/app/handlers/handlers_test.go
> +		if test.isError {
У меня нет идей, как применить для данного случая ранний return, кроме как разделить тест на два независимых и вообще избавиться от условия

2024-02-13 06:28 UTC, popoffvg commented on internal/app/handlers/handlers_test.go
> +		if test.isError {
```
if test.isError {
     assert.Equal(t, test.want.message, string(respBody))
     conitnue
}
```

2024-02-14 06:30 UTC, merged